sudo: required
services:
  - docker

before_install:
  - docker build -t rcbfredeluces/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rcbfredeluces/complex-test npm test -- --coverage

after_success:
  - docker build -t rcbfredeluces/complex-client ./client
  - docker build -t rcbfredeluces/complex-nginx ./nginx
  - docker build -t rcbfredeluces/complex-server ./server
  - docker build -t rcbfredeluces/complex/worker ./worker

# login to  the docker CLI
  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_ID -p=$DOCKER_PASSWORD
# take images and push into dockerhub
  - docker push rcbfredeluces/complex-client
  - docker push rcbfredeluces/complex-nginx
  - docker push rcbfredeluces/complex-server
  - docker push rcbfredeluces/complex-worker