sudo: required
services:
  - docker

before_install:
  - docker build -t rcbfredeluces/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rcbfredeluces/complex-test npm test -- --coverage

after_success:
  - docker build -t rcbfredeluces/complexclient:latest ./client
  - docker build -t rcbfredeluces/complexnginx:latest ./nginx
  - docker build -t rcbfredeluces/complexserver:latest ./server
  - docker build -t rcbfredeluces/complexworker:latest ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  - docker push rcbfredeluces/complexclient:latest
  - docker push rcbfredeluces/complexnginx:latest
  - docker push rcbfredeluces/complexserver:latest
  - docker push rcbfredeluces/complexworker:latest

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-788723507982
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY