sudo: required
services:
  - docker

before_install:
  - docker build -t rcbfredeluces/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rcbfredeluces/complex-test npm test -- --coverage

after_success:
  - docker build -t rcbfredeluces/complexclient ./client
  - docker build -t rcbfredeluces/complexnginx ./nginx
  - docker build -t rcbfredeluces/complexserver ./server
  - docker build -t rcbfredeluces/complexworker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rcbfredeluces/complexclient
  - docker push rcbfredeluces/complexnginx
  - docker push rcbfredeluces/complexserver
  - docker push rcbfredeluces/complexworker